"""Added api key info for student and teacher

Revision ID: 075ca42c09e6
Revises: 7ab3f0560787
Create Date: 2023-10-12 17:06:10.859553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075ca42c09e6'
down_revision = '7ab3f0560787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lnbits_api_key', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('lnbits_api_key')

    # ### end Alembic commands ###
