"""class and lesson details

Revision ID: 8fa46e3bd639
Revises: ef568ec74232
Create Date: 2023-10-13 10:47:15.410534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fa46e3bd639'
down_revision = 'ef568ec74232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_student', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('status_teacher', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('status_teacher')
        batch_op.drop_column('status_student')

    # ### end Alembic commands ###
