"""improvments on app.py and models.py

Revision ID: a38db5dd6af5
Revises: 075ca42c09e6
Create Date: 2023-10-13 09:41:07.214439

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a38db5dd6af5'
down_revision = '075ca42c09e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('material_link', sa.String(length=250), nullable=True),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('escrow', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escrow_created_at'), ['created_at'], unique=False)
        batch_op.drop_constraint('escrow_class_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'lesson', ['class_id'], ['id'])

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_available_date'), ['available_date'], unique=False)
        batch_op.drop_constraint('schedule_class_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'lesson', ['class_id'], ['id'])

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_created_at'))

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('schedule_class_id_fkey', 'class', ['class_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_schedule_available_date'))

    with op.batch_alter_table('escrow', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('escrow_class_id_fkey', 'schedule', ['class_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_escrow_created_at'))

    op.create_table('class',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('material_link', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='class_pkey')
    )
    op.drop_table('lesson')
    # ### end Alembic commands ###
