"""improvments on app.py and models.py

Revision ID: ef568ec74232
Revises: a38db5dd6af5
Create Date: 2023-10-13 10:26:18.205349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef568ec74232'
down_revision = 'a38db5dd6af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('material_link', sa.String(length=250), nullable=True),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('escrow', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escrow_created_at'), ['created_at'], unique=False)
        batch_op.create_foreign_key(None, 'lesson', ['class_id'], ['id'])

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_available_date'), ['available_date'], unique=False)
        batch_op.create_foreign_key(None, 'lesson', ['class_id'], ['id'])

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_created_at'))

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_schedule_available_date'))

    with op.batch_alter_table('escrow', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_escrow_created_at'))

    op.drop_table('lesson')
    # ### end Alembic commands ###
